Fixed #9: nan value causes alert to be skipped
copenhagenatomics/CA_DataUploader pull request #13
Opened 2020-09-10 11:35 UTC by freddyrios

2020-09-10 11:37 UTC, freddyrios commented
Note: to be rebased and merged to master after completing https://github.com/copenhagenatomics/CA_DataUploader/pull/11

2020-09-11 04:37 UTC, copenhagenatomics requested changes
This new code is more difficult to read than before. Thus it is more likely to catch errors in the future. 
If "IsInteger" is the main reason behind the change. Then I suggest we delete it. I am not sure we will ever need it. Or at least move the RawCheckValue function outside the function as a private method.

2020-09-11 06:57 UTC, freddyrios commented
> This new code is more difficult to read than before. Thus it is more likely to catch errors in the future.
> If "IsInteger" is the main reason behind the change. Then I suggest we delete it. I am not sure we will ever need it. Or at least move the RawCheckValue function outside the function as a private method.

@copenhagenatomics the change was not due to the is integer issue mentioned at #6. In fact, it makes a poor job for that use case, because while it prevents a repeated number from triggering it does not trigger on different integers. That is, in the following sequence it only triggers twice, instead of 3 times: 
- 123.2
- 124
- 125
- 125.3
- 126

Instead, the change was done precisely to fix the referenced issues, that is:
- #9 
- #7 

Here are some ways of fixing NaN causing alerts to be skipped on the next value:
1. check if the last value was NaN and depending on the expression, the boundary value and the new measured value decide whether to skip
2. add is NaN checks to the different comparisons in the existing switch statement
3. use a negated comparison when comparing the old value in the existing switch statement i.e. return newValue > Value && !(newValue > Value)
4. same concept as previous point, but instead of spreading the negation in the switch statements, extract a method/local function and use it for both the match (newvalue) and no match checks (oldvalue).

Went with option 4, as 1 to 3 are more error prone and likely more complex in practice.

Regarding moving from a [local function](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/local-functions) to a private method, I take it then it is one of our code style choices to stick to private methods in general, right? Here is what the case that link makes for local functions:
>Local functions make the intent of your code clear. Anyone reading your code can see that the method is not callable except by the containing method. For team projects, they also make it impossible for another developer to mistakenly call the method directly from elsewhere in the class or struct.

2020-09-11 07:02 UTC, freddyrios commented on CA_DataUploaderLib/IOconf/IOconfAlert.cs
> +            return res;
@copenhagenatomics is it easier to read if we do this instead?

```
var res = _isFirstCheck ? RawCheckValue(newValue) : (RawCheckValue(newValue) && !RawCheckValue(oldValue))
_isFirstCheck = false;
return res;
```

or even:
```
var newMatched = RawCheckValue(newValue) ;
var res = _isFirstCheck ? newMatched : (newMatched && !RawCheckValue(oldValue))
_isFirstCheck = false;
return res;
```

2020-09-14 06:51 UTC, freddyrios commented on CA_DataUploaderLib/IOconf/IOconfAlert.cs
> +            return res;
closing this conversation as used a slightly different approach

2020-09-14 14:00 UTC, merged